package jerseyexample;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class PostDao {
	// JDBC driver name and database URL 
	   static final String JDBC_DRIVER = "org.h2.Driver";   
	   static final String DB_URL = "jdbc:h2:C:\\Users\\getterundsetter\\Desktop\\db";  
	   
	   //  Database credentials 
	   static final String USER = "sa"; 
	   static final String PASS = ""; 
	   protected Connection conn = null;
	   
	   //constructor with database connection
	public PostDao() {
		 
		//"empty" variable of type Statement
	      Statement stmt = null; 
	      
	      try { 
	         //Register JDBC driver 
	         Class.forName(JDBC_DRIVER); 
	             
	         //Open a connection 	        
	         conn = DriverManager.getConnection(DB_URL);  
	         
	         //Execute a query 
	         System.out.println("Creating table in given database..."); 
	         stmt = conn.createStatement(); 
	         String sql = "CREATE TABLE IF NOT EXISTS POSTS " + 
	                 "(id INTEGER not NULL AUTO_INCREMENT, " + 
	                 " content VARCHAR, " +
	                 " PRIMARY KEY ( id ))";      		 
	       		
	         stmt.executeUpdate(sql);
	       	         
	         //Clean-up environment 
	         stmt.close(); 	      
	      } catch(SQLException se) { 
	         //Handle errors for JDBC 
	         se.printStackTrace(); 
	      } catch(Exception e) { 
	         //Handle errors for Class.forName 
	         e.printStackTrace(); 
	      } finally { 
	         //finally block used to close resources 
	         try{ 
	            if(stmt!=null) stmt.close(); 
	         } catch(SQLException se2) { 
	         } 
	        
	      } 
	  
	   } 
		
	
	
	//method for inserting a Post into a Database
	public Post insertPost(String content) {
		//"empty" variable of type Post 
		Post ret =null;
		
		//try-catch-block for exception handling
		//connection to database and use of prepared statement to prevent SQL-injection --> "?" placeholder 
		//autogenerated keys --> auto increment; each entry gets own unique ID based on location in the database
		try (PreparedStatement stmt = conn.prepareStatement("INSERT INTO POSTS (content) VALUES (?)",Statement.RETURN_GENERATED_KEYS)){
			//placeholder "?" of Values is set to "content"
			stmt.setString(1, content);
			//execute statement
			int lines = stmt.executeUpdate();
			//prints line number
			System.out.println("lines: " + lines);
			//get generated keys
			ResultSet rs = stmt.getGeneratedKeys();
			//moves the cursor one row forward
			rs.next();
			//get the first position in database			
			int id = rs.getInt(1);
			//set variable ret to new Post object with values of content and id
			ret = new Post(content, id);
			//commit changes to database
			conn.commit();
		}
		//catch block handles exceptions
		catch (Exception e) {
			e.printStackTrace();
		}
		//returns variable ret
		return ret;
	}
	//select one specific post
	public Post readPost(int id) {
		//"empty" variable of type Post
		Post ret=null;
		//try-catch-block for exception handling
		//connection to database and use of prepared statement to prevent SQL-injection --> "?" placeholder		
		try (PreparedStatement stmt = conn.prepareStatement("SELECT * FROM POSTS WHERE id=?")){
			//placeholder "?" of id is set to "id"
			stmt.setInt(1, id);
			//excutes query 
			ResultSet dummy = stmt.executeQuery();
			//moves cursor one row forward from current position (SQL-database start at row 0)
			dummy.next();
			//gets Post content of selected Post
			String content = dummy.getString(2);
			//set variable ret to new Post object with values of content and id
			ret = new Post(content, id);
		}//catch block handles exceptions and prints error messages
		catch (Exception e) {
			e.printStackTrace();
		}
		//returns ret (selected Post)
		return ret;		
	}
	//select all posts
	public List<Post> readPosts() {
		//creates list of type Post
		List<Post> ret = new ArrayList<Post>();
		
		//try-catch-block for exception handling
		//		connection to database and use of prepared statement to prevent SQL-injection --> "?" placeholder
		try (PreparedStatement stmt = conn.prepareStatement("SELECT * FROM POSTS")){
			//excute query
			ResultSet dummy = stmt.executeQuery();
			//while loop: moves cursor to next row until there is no more entry in database
			while(dummy.next()) {
				//gets id from Post of current row
				int id = dummy.getInt(1);
				//gets content from Post of current row
				String content = dummy.getString(2);
				//set variable ret to new Post object with values of content and id
				Post post = new Post(content, id);
				//adds Post-Object to Post-list
				ret.add(post);
			}
		} //catch block handles exceptions and prints error messages
		catch (Exception e) {
			e.printStackTrace();
		}
		return ret;	
	}
}

